version: '3'
services:
  task-stable-timew-stable:
    build:
        context: .
        dockerfile: test/docker/Dockerfile
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
