version: '3'
services:
  task-stable-timew-stable:
    build:
      context: .
      dockerfile: test/docker/Dockerfile
      args:
        TASK_BRANCH: "stable"
        TIMEW_BRANCH: "stable"
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true

  task-develop-timew-stable:
    build:
      context: .
      dockerfile: test/docker/Dockerfile
      args:
        TASK_BRANCH: "develop"
        TIMEW_BRANCH: "stable"
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true

  task-stable-timew-develop:
    build:
      context: .
      dockerfile: test/docker/Dockerfile
      args:
        TASK_BRANCH: "stable"
        TIMEW_BRANCH: "develop"
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true

  task-develop-timew-develop:
    build:
      context: .
      dockerfile: test/docker/Dockerfile
      args:
        TASK_BRANCH: "develop"
        TIMEW_BRANCH: "develop"
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
