name: tests
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "task [stable] & timew [stable]"
            runner: ubuntu-latest
            container: task-stable-timew-stable
          - name: "task [develop] & timew [stable]"
            runner: ubuntu-latest
            container: task-develop-timew-stable
          - name: "task [stable] & timew [develop]"
            runner: ubuntu-latest
            container: task-stable-timew-develop
          - name: "task [develop] & timew [develop]"
            runner: ubuntu-latest
            container: task-develop-timew-develop

    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.continue-on-error == true }}
    steps:
      - uses: actions/checkout@v2
      - name : Login to GHCR
        uses : docker/login-action@v2
        with :
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.name }}
        env:
          DOCKER_REGISTRY: ghcr.io
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.container }}
        run: docker-compose build ${CONTAINER}
      - name: Test ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.container }}
        run: docker-compose run ${CONTAINER}
